// 1.13.1: LAB*: Program: ASCII cat

import java.util.Scanner;

public class LabProgram {
   public static void main(String[] args) {
      Scanner scnr = new Scanner(System.in);
      
      String name = scnr.nextLine();

      System.out.println("      /\\_/\\");
      System.out.println(" /\\  / o o \\");
      System.out.println("//\\\\ \\~(*)~/");
      System.out.println("`  \\/   ^ /");
      System.out.println("   | \\|| ||");
      System.out.println("   \\ '|| ||");
      System.out.println("    \\)()-())");
      System.out.println("My cat " + name);
      
   }
}
