// 3.28.1: LAB 3.5.1: Exact change (pseudocode) -- see next for actual code

public class Main {
   public static void main(String[] args) {
      
      System.out.println("Write your pseudocode below as comments.");
      
      // create scanner
      
      // impliment scanner to read input
      
      // declare variables as ints and use modulos to get decimals 
      // (Dollars, Quarters, Dimes, Nickles, Pennies)
      
      // no change if and print statement
      
      // dollars if-else and print statements
      
      // quarters if-else and print statements
      
      // dimes if-else and print statements
      
      // nickels if-else and print statements
      
      // pennies if-else and print statements
      
   }
}
